version: 0.2
phases:
  install:
    commands:
    - npm install -g yarn
  build:
    commands:
    - yarn install --production
    - yarn release
    - aws cloudformation package --template-file template.yml --s3-bucket $SERVICE_DEPLOYMENT_BUCKET --output-template-file processed-template.yml

artifacts:
  files:
  - processed-template.yml
