version: 0.2
phases:
  install:
    commands:
    - npm install -g yarn
  build:
    commands:
    - yarn install --production
    - yarn release

artifacts:
  type: zip
  files:
  - "**/*"
  base-directory: build
