Transform: AWS::Serverless-2016-10-31
Resources:
  ApiEndpointFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api
            Method: GET
